# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 566cd1c46a8ba2c907a4243dc72c40d16a5ffc2102cfbfbb444784e66ef2c7939f776f62119407f2ed0657c8b331e8dcbb65a2a0359d2cf1b130fe8cdcfc4401

test:
  secret_key_base: c25c40b235a58bd02de7ea0c0805dea445a4992432a9fba9f67c89d1476b9117060ac4c938ee9a2b29fc939fe878ef6f681cfa735fe0c5c654cf8f12a430c8b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
